version: '3'
services:
  scc-state:
    image: scc-state
    ports:
      - 7777:7777
  scc-broker1:
    image: scc-broker
    ports:
      - 8888:8888
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SCC_BROKER_SERVER_PORT=8888
  scc-broker2:
    image: scc-broker
    ports:
      - 9999:9999
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SCC_BROKER_SERVER_PORT=9999
  test-app1:
    image: test-app
    ports:
      - 8000:8000
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SOCKETCLUSTER_PORT=8000
  test-app2:
    image: test-app
    ports:
      - 8001:8001
    environment:
      - SCC_STATE_SERVER_HOST=scc-state
      - SOCKETCLUSTER_PORT=8001
  portainer:
    image: "portainer/portainer:1.20.2"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock